import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*
        Some browser extensions (e.g. Clip/Shortcut managers) can inject attributes
        into DOM nodes before React hydrates which causes Next.js to warn about
        mismatched attributes such as `cz-shortcut-listen`. This warning is
        harmless in many cases. We suppress the hydration warning on the body
        element while keeping the server-rendered className deterministic.

        See: https://nextjs.org/docs/messages/react-hydration-error
      */}
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
